language: python

before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - export ANACONDA_PATH=$HOME/miniconda
  - bash miniconda.sh -b -p $ANACONDA_PATH
  - source "$ANACONDA_PATH/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda env create -f environment.yaml

# command to run tests
script:
  - conda activate ecs
  # Install package
  - pip install -e . -v
  # Run Linters and Formatters
  - tools/run_linters_and_formatters.sh
  # Run Python tests
  - pytest unit_tests
  # Run C++ tests
  - rm -rf build
  - mkdir build
  - cd build
  - cmake ..
  - make ecs_cpp_tests
  - ./ecs_cpp_tests